# SPDX-FileCopyrightText: 2026 Luke Galea
#
# SPDX-License-Identifier: MIT

defmodule AshStrangler.Verifiers.VerifyNoUpserts do
  @moduledoc """
  Upserts and `INSTEAD OF` triggers are mutually exclusive. This catches it at
  compile time rather than at 2am.

  ## The mechanism

  `INSERT … ON CONFLICT` works against an **auto-updatable** view with a
  column-list conflict target. Once an `INSTEAD OF` trigger exists on that view,
  it does not: `DO NOTHING` is *accepted and then inert*, and `DO UPDATE` errors.
  Postgres does not warn about the first case.

  So an `INSTEAD OF` trigger is a **trade, not an addition**. It buys governed
  writes; it costs upserts, correct `RETURNING`, and
  `WITH CHECK OPTION`. This verifier makes the cost visible at the point where
  the trade is made.

  ## Why the error names the strategy

  Verified against `ash_authentication` 4.14.1: OAuth2 and OIDC register actions
  **cannot be defined without an upsert** — the strategy's transformer validates
  `upsert?: true` and a non-nil `upsert_identity`, and errors otherwise. The same
  is true of the `UserIdentity` resource.

  That means "action `:register_with_oauth2` requires an upsert" is a true but
  useless message: the author never wrote `upsert? true` and cannot remove it.
  The fix is to use `writes: :auto`, or to not strangle that resource. The error
  says so.

  The `password` strategy does **not** upsert, so password-only authentication
  is migratable on the trigger path. That is the common case for a legacy
  monolith.
  """

  use Spark.Dsl.Verifier

  alias Spark.Dsl.Verifier

  # Actions ash_authentication generates that are upserts by construction.
  @strategy_actions %{
    register_with_oauth2: "the oauth2 strategy",
    register_with_oidc: "the oidc strategy",
    upsert: "the user_identity resource"
  }

  @impl true
  def verify(dsl) do
    with true <- AshStrangler.Info.strangled?(dsl),
         :triggers <- AshStrangler.Info.writes(dsl) do
      case upsert_actions(dsl) do
        [] -> :ok
        actions -> {:error, error(dsl, actions)}
      end
    else
      _ -> :ok
    end
  end

  defp upsert_actions(dsl) do
    dsl
    |> Verifier.get_entities([:actions])
    |> Enum.filter(&Map.get(&1, :upsert?, false))
    |> Enum.map(& &1.name)
  end

  defp error(dsl, actions) do
    {strategy_owned, user_owned} =
      Enum.split_with(actions, &Map.has_key?(@strategy_actions, &1))

    Spark.Error.DslError.exception(
      module: Verifier.get_persisted(dsl, :module),
      path: [:strangler, :source, :writes],
      message: """
      This resource writes through `INSTEAD OF` triggers, but these actions are upserts:

        #{Enum.map_join(actions, "\n  ", &inspect/1)}

      `INSERT … ON CONFLICT` does not work against a view with an INSTEAD OF
      trigger. `DO NOTHING` is accepted and silently does nothing; `DO UPDATE`
      errors. Postgres does not warn about the first, so this would surface as
      rows that quietly fail to appear.
      #{strategy_note(strategy_owned)}#{user_note(user_owned)}
      Options:

        1. Look at WHICH mapping forced the triggers, and see whether it can be
           expressed as a combinator that needs a weaker mechanism.
           `mix ash_strangler.check` prints the classification per attribute.
           `AshStrangler.Mechanism` only reaches `:instead_of` for a mapping that
           writes across relations or writes more than one legacy column — a
           `decode`d status column, which 0.1 would have charged triggers for, does
           not.

        2. `writes: :auto` — rely on view auto-updatability, which keeps upserts,
           correct RETURNING and WITH CHECK OPTION. An override, so the mapping
           still has to be one Postgres considers auto-updatable.

        3. Do not strangle this resource. Cut it over directly instead.
      """
    )
  end

  defp strategy_note([]), do: "\n"

  defp strategy_note(actions) do
    """

      These are generated by ash_authentication and CANNOT be made non-upsert —
      the strategy's own transformer requires `upsert? true`:

        #{Enum.map_join(actions, "\n    ", fn a -> "#{inspect(a)} — #{@strategy_actions[a]}" end)}

      Removing the upsert is not available to you. Option 1 or 2 below is.
    """
  end

  defp user_note([]), do: ""

  defp user_note(actions) do
    """
      These are defined in this resource, so a third option is to remove
      `upsert? true` from them if the idempotency is not actually needed:

        #{Enum.map_join(actions, "\n    ", &inspect/1)}

    """
  end
end
