# SPDX-FileCopyrightText: 2026 Luke Galea
#
# SPDX-License-Identifier: MIT

defmodule AshStrangler.Verifiers.VerifyTwin do
  @moduledoc """
  The `source` module must be a usable twin, and every column the mapping reads
  must exist on it.

  ## What this replaces

  Nothing, and that is the point. In 0.1 `source "legacy.users"` was a string and
  `from: "coalesce(first_name,'') || ' '"` was a string, so a typo in a column name
  was not detectable at all — it reached Postgres at `mix ash.migrate` time, or, if
  the typo happened to name a *different real column*, it never surfaced. The
  diagram's regex was the closest thing to a check, and its own moduledoc conceded
  it was a heuristic.

  With a twin, a column reference either resolves or it does not, and this is where
  it is decided.

  ## The staleness this cannot decide

  The twin is generated by introspection, so it is a **snapshot**. This verifier
  proves the mapping agrees with the twin; it cannot prove the twin agrees with the
  database. A column the legacy application's next migration added is invisible to
  both.

  That half is `mix ash_strangler.check`, which diffs every twin against
  `information_schema` and reports the difference. Saying so plainly matters: a
  verifier that appeared to check the legacy schema but only checked a snapshot of
  it would be trusted for something it does not do.
  """

  use Spark.Dsl.Verifier

  alias AshStrangler.{Info, Lens, Twin}
  alias Spark.Dsl.Verifier

  @impl true
  def verify(dsl) do
    with true <- Info.strangled?(dsl),
         twin = Info.twin(dsl),
         :ok <- verify_twin_module(dsl, twin) do
      verify_references(dsl, twin)
    else
      false -> :ok
      {:error, error} -> {:error, error}
    end
  end

  defp verify_twin_module(dsl, twin) do
    cond do
      not Twin.twin?(twin) ->
        {:error, not_a_twin(dsl, twin)}

      Ash.Resource.Info.attributes(twin) == [] ->
        {:error, empty_twin(dsl, twin)}

      true ->
        :ok
    end
  end

  # Every `{relationship_path, attribute}` any lens reads, checked against the
  # twin. A path is resolved relationship by relationship, so a mapping reading
  # `expr(address.city)` fails on `:address` if the twin has no such relationship
  # and on `:city` if the destination has no such attribute -- and the message says
  # which.
  defp verify_references(dsl, twin) do
    dsl
    |> Lens.for_resource()
    |> Enum.flat_map(fn lens -> Enum.map(lens.sources, &{lens, &1}) end)
    |> Enum.reduce_while(:ok, fn {lens, {path, attribute}}, :ok ->
      case resolve(twin, path, attribute) do
        :ok -> {:cont, :ok}
        {:error, message} -> {:halt, {:error, unresolved(dsl, lens, path, attribute, message)}}
      end
    end)
  end

  defp resolve(twin, path, attribute) when path != [] do
    # `joins_for/2` rather than `resource_at/2` alone, because only the former checks
    # cardinality. A `has_many` cannot be joined into a view: it would multiply
    # rows, so one legacy account with three addresses would become three records
    # where the old application had one -- the fan-out failure this package exists to
    # refuse.
    #
    # `Info.joins/1` swallows that error and returns `[]`, which is right for a
    # diagram but means nothing else notices: the view's `SELECT` would reference an
    # unjoined `addresses.city` and PostgreSQL would reject it at `mix ash.migrate`
    # time, in whichever environment ran first.
    with {:ok, _joins} <- Twin.joins_for(twin, path) do
      resolve_attribute(twin, path, attribute)
    end
  end

  defp resolve(twin, path, attribute), do: resolve_attribute(twin, path, attribute)

  defp resolve_attribute(twin, path, attribute) do
    case Twin.resource_at(twin, path) do
      {:error, message} ->
        {:error, message}

      {:ok, resource} ->
        # `exists(payments, ...)` puts the *relationship* in the reference list, so
        # a name that resolves to either is resolved.
        if Ash.Resource.Info.attribute(resource, attribute) ||
             Ash.Resource.Info.relationship(resource, attribute) do
          :ok
        else
          {:error,
           "#{inspect(resource)} has no attribute #{inspect(attribute)}. It declares: " <>
             (resource |> Twin.columns() |> Enum.sort() |> Enum.map_join(", ", &inspect/1))}
        end
    end
  end

  defp not_a_twin(dsl, twin) do
    Spark.Error.DslError.exception(
      module: Verifier.get_persisted(dsl, :module),
      path: [:strangler, :source],
      message: """
      #{inspect(twin)} is not usable as a strangler `source`.

      `source` takes a **twin**: the legacy relation declared as an ordinary Ash
      resource on `AshPostgres.DataLayer`, with a `table`. In 0.1 it took a
      relation name as a string, and replacing that is what makes `expr(first_name)`
      mean anything at all.

      Generate one from the live database rather than typing it:

          mix ash_strangler.gen.twin --relation legacy.users --module #{inspect(twin)}

      See `AshStrangler.Twin`.
      """
    )
  end

  defp empty_twin(dsl, twin) do
    Spark.Error.DslError.exception(
      module: Verifier.get_persisted(dsl, :module),
      path: [:strangler, :source],
      message: """
      #{inspect(twin)} declares no attributes, so no mapping over it can resolve.

      An empty twin usually means it was generated against a relation that does not
      exist, or that the generator was pointed at the wrong schema. Regenerate it:

          mix ash_strangler.gen.twin --relation <schema>.<table> --module #{inspect(twin)}
      """
    )
  end

  defp unresolved(dsl, lens, path, attribute, message) do
    reference =
      case path do
        [] -> inspect(attribute)
        path -> Enum.map_join(path ++ [attribute], ".", &to_string/1)
      end

    Spark.Error.DslError.exception(
      module: Verifier.get_persisted(dsl, :module),
      path: [:strangler, :source, lens.combinator, lens.attribute],
      message: """
      The mapping for #{inspect(lens.attribute)} reads `#{reference}`, which does not resolve.

      #{message}

      Either the reference is a typo, or the twin is stale -- it is a snapshot of
      the legacy schema, so a column added since it was generated is invisible.
      Regenerate it and re-run:

          mix ash_strangler.gen.twin #{inspect(Info.twin(dsl))}
          mix ash_strangler.check
      """
    )
  end
end
