# SPDX-FileCopyrightText: 2026 Luke Galea
#
# SPDX-License-Identifier: MIT

defmodule AshStrangler.Verifiers.VerifyNotMigrated do
  @moduledoc """
  A strangler resource must declare `migrate? false`.

  ## The collision this prevents

  A strangler resource's `table` names a **view**, not a table. With the
  AshPostgres default of `migrate? true`, `mix ash.codegen` emits a
  `create table` for it — and then the view DDL tries to create a view of the
  same name. Verified by generating it:

  ```elixir
  create table(:users, primary_key: false, prefix: "strangler") do
    ...
  end

  execute(\"\"\"
  CREATE OR REPLACE VIEW "strangler"."users" AS ...
  \"\"\")
  ```

  `CREATE OR REPLACE VIEW` on an existing *table* fails, so the migration
  cannot run at all. Loud rather than silent, but only at `mix ash.migrate`
  time, in whatever environment ran it first.

  ## Why the SQL is not emitted through `custom_statements` any more

  The obvious fix — `migrate? false` — has a second effect that is easy to
  miss: `AshPostgres.MigrationGenerator` splits resources into managed and
  unmanaged, and **only managed resources produce snapshots**, which is where
  `custom_statements` are read from. So `migrate? false` silently drops the
  generated view, index and trigger statements too. Verified both ways.

  There is therefore no configuration in which `custom_statements` works for a
  view-backed resource: `true` collides, `false` discards. The DDL is emitted by
  `mix ash_strangler.gen.migration` instead, which is also what AshPostgres's
  own `mix ash_postgres.gen.resources --include-views` implies by writing
  `migrate? false` next to a comment saying migrations for views are manual.
  """

  use Spark.Dsl.Verifier

  alias Spark.Dsl.Verifier

  # Phase-dependent, and that is the whole point of the phase model. In
  # `:read_from_legacy` and `:dual_write` the resource's `table` is a view over
  # legacy tables, so Ash must not create it. In `:read_from_new` the direction
  # has flipped: a real Ash-owned table exists and the *legacy* name is the
  # view, so `migrate? true` is not merely allowed, it is required.
  @view_backed_phases [:read_from_legacy, :dual_write]

  @impl true
  def verify(dsl) do
    with true <- AshStrangler.Info.strangled?(dsl),
         phase when phase in @view_backed_phases <- AshStrangler.Info.strangler_phase!(dsl),
         true <- migrated?(dsl) do
      {:error, error(dsl, phase)}
    else
      _ -> :ok
    end
  end

  # Reads the option directly rather than through AshPostgres.DataLayer.Info,
  # so this still works for a resource whose data layer is something else
  # entirely (in which case there is no `postgres` section and nothing to
  # complain about).
  defp migrated?(dsl) do
    Verifier.get_persisted(dsl, :data_layer) == AshPostgres.DataLayer and
      Verifier.get_option(dsl, [:postgres], :migrate?, true)
  end

  defp error(dsl, phase) do
    Spark.Error.DslError.exception(
      module: Verifier.get_persisted(dsl, :module),
      path: [:postgres, :migrate?],
      message: """
      A resource in phase #{inspect(phase)} must set `migrate? false`.

          postgres do
            table "users"
            schema "strangler"
            repo MyApp.Repo
            migrate? false
          end

      Its `table` names a VIEW. Left at the default, `mix ash.codegen` emits a
      `create table` for that name and the view DDL then fails to create a view
      over it, so the migration cannot run.

      The compatibility DDL is generated by `mix ash_strangler.gen.migration`
      rather than by `mix ash.codegen`. It has to be: with `migrate? false` the
      migration generator does not produce a snapshot for this resource, and
      `custom_statements` are only read from snapshots — so there is no setting
      in which the ordinary codegen path can carry it.
      """
    )
  end
end
