# SPDX-FileCopyrightText: 2026 Luke Galea
#
# SPDX-License-Identifier: MIT

defmodule AshStrangler.Test.Legacy do
  @moduledoc """
  Domain for the **twins** — the legacy relations, declared as ordinary Ash
  resources.

  A twin is not part of the application's model. It is the old schema, typed, so
  `expr(first_name)` has something to resolve against. See `AshStrangler.Twin`.

  In a real project these are generated by `mix ash_strangler.gen.twin`, which
  reads `information_schema` and `pg_index`. They are written by hand here for the
  same reason `AshStrangler.Test.LegacySchema` writes the DDL by hand: the fixture
  has to exist before the generator can be pointed at it.
  """

  use Ash.Domain, validate_config_inclusion?: false

  resources do
    resource AshStrangler.Test.Legacy.Users
  end
end

defmodule AshStrangler.Test.Legacy.Users do
  @moduledoc """
  The twin for `legacy.users`.

  ## `state` is an `:atom` with `one_of`, and that is load-bearing

  The column is `text NOT NULL DEFAULT 'active'`. Typing it `:string` would be
  closer to the storage and would make the mapping over it **unprovable**: with no
  declared value set there is no domain to enumerate, so `AshStrangler.Obligations`
  could only emit `GetTotal` as a SQL assertion for `mix ash_strangler.check` to
  measure later.

  `:atom` with `one_of` is Ash's vocabulary for *this text column holds one of
  these values*, and it is what makes the obligation decidable at compile time — so
  a `decode` that forgets `passive` fails the build rather than corrupting three of
  five lifecycle states in production, which is what 0.1 did.

  `mix ash_strangler.gen.twin` writes this form automatically when the legacy
  column carries a `CHECK ... IN (...)` constraint or a Postgres enum type. When it
  does not, the twin gets `:string` and the obligation degrades to a measured one —
  which is the honest outcome, not a failure.
  """

  use Ash.Resource,
    domain: AshStrangler.Test.Legacy,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshStrangler.Twin]

  postgres do
    table "users"
    schema "legacy"
    repo AshStrangler.TestRepo
    # Ash does not own this table and never will.
    migrate? false
  end

  attributes do
    attribute :id, :integer, primary_key?: true, allow_nil?: false, public?: true
    attribute :login, :string, allow_nil?: false, public?: true
    attribute :email, :string, public?: true
    attribute :first_name, :string, public?: true
    attribute :last_name, :string, public?: true

    attribute :state, :atom do
      allow_nil? false
      public? true
      constraints one_of: [:passive, :pending, :active, :suspended, :deleted]
    end

    # Deliberately naive. The resource attribute it feeds is `:utc_datetime_usec`,
    # and `zone:` is what bridges them -- a mapping that only ever ran against an
    # already-aware column would be testing nothing.
    attribute :deleted_at, :naive_datetime, public?: true
    attribute :salt, :string, public?: true
    attribute :crypted_password, :string, public?: true
    attribute :created_at, :naive_datetime, public?: true
  end

  identities do
    # Replaces 0.1's `index "index_users_on_login", unique: true, columns: ["login"]`,
    # which restated in the mapping something `pg_index` can be asked about.
    identity :index_users_on_login, [:login]
  end

  actions do
    defaults [:read]
  end
end
