# SPDX-FileCopyrightText: 2026 Luke Galea
#
# SPDX-License-Identifier: MIT

defmodule AshStrangler.Migration do
  @moduledoc """
  Assembles every generated statement for a resource, in dependency order.

  This is the single place that knows the *order* the compatibility layer has
  to be built in — view, then key index, then `INSTEAD OF` triggers, then the
  notify trigger — and it is shared by `mix ash_strangler.gen.migration` and by
  the test harness, so the suite exercises exactly what a migration would run.

  Statements are `%{name: atom, up: String.t(), down: String.t()}` with **one
  SQL command each**. That is not stylistic: Ecto sends a migration's
  `execute/1` string on the extended protocol, which rejects multiple commands
  with `42601 cannot insert multiple commands into a prepared statement`.
  """

  alias AshStrangler.Sql

  @doc """
  Every statement for `resource`, ordered so that running them in sequence
  works from an empty database.

  Returns `[]` for a resource with no strangler mapping.
  """
  @spec statements(Ash.Resource.t()) :: [%{name: atom(), up: String.t(), down: String.t()}]
  def statements(resource) do
    if AshStrangler.Info.strangled?(resource) do
      case AshStrangler.Info.strangler_phase!(resource) do
        :decommissioned ->
          # Nothing is generated: the compatibility layer is gone and the
          # mapping is vestigial. Removing the resource's `strangler` block
          # entirely is the next edit.
          []

        :read_from_new ->
          Sql.ReverseView.build(resource) ++ Sql.Notify.build(resource)

        phase ->
          %{view: view, key_index: key_index} = Sql.View.build(resource)
          triggers = if phase == :dual_write, do: Sql.Triggers.build(resource), else: []

          Enum.reject([view, key_index], &is_nil/1) ++ triggers ++ Sql.Notify.build(resource)
      end
    else
      []
    end
  end

  @doc """
  Every strangler-mapped resource across the configured domains, or across
  `domains` when given.
  """
  @spec resources(list(module()) | nil) :: [Ash.Resource.t()]
  def resources(domains \\ nil) do
    (domains || Ash.Info.domains(Mix.Project.config()[:app]))
    |> Enum.flat_map(&Ash.Domain.Info.resources/1)
    |> Enum.filter(&AshStrangler.Info.strangled?/1)
    |> Enum.uniq()
  end

  @doc """
  Renders an Ecto migration module for the given resources.

  `down` reverses the statement order, since a trigger cannot outlive the view
  it is attached to and a function cannot be dropped before the trigger that
  executes it. That is a luxury the `custom_statements` path did not have —
  it runs every `down` before every `up`, in list order, which is why those
  statements had to be individually order-independent.
  """
  @spec render(String.t(), [Ash.Resource.t()]) :: String.t()
  def render(module_name, resources) do
    statements = Enum.flat_map(resources, &statements/1)

    ups = Enum.map_join(statements, "\n", &render_execute(&1.up))
    downs = statements |> Enum.reverse() |> Enum.map_join("\n", &render_execute(&1.down))

    """
    defmodule #{module_name} do
      @moduledoc \"\"\"
      Strangler compatibility layer, generated by `mix ash_strangler.gen.migration`.

      Covers: #{Enum.map_join(resources, ", ", &inspect/1)}

      Regenerate rather than hand-editing. Every statement is idempotent
      (`CREATE OR REPLACE`, `IF NOT EXISTS`), so re-running this after a mapping
      change is safe.
      \"\"\"

      use Ecto.Migration

      def up do
    #{ups}  end

      def down do
    #{downs}  end
    end
    """
  end

  defp render_execute(sql) do
    """
        execute(\"\"\"
    #{String.trim_trailing(sql)}
        \"\"\")
    """
  end
end
