# SPDX-FileCopyrightText: 2026 Luke Galea
#
# SPDX-License-Identifier: MIT

defmodule AshStrangler.Resource do
  @moduledoc """
  Ash resource extension for strangler-fig migrations.

      use Ash.Resource,
        data_layer: AshPostgres.DataLayer,
        extensions: [AshStrangler.Resource]

  Adds the `strangler` section (see `AshStrangler.Dsl`) and the verifiers that
  decide whether a mapping is legal.

  ## Where each part lives

  | | |
  |---|---|
  | what a mapping *means*, both ways | `AshStrangler.Lens` |
  | what is *legal* | the modules under `AshStrangler.Verifiers` |
  | what can be *proven* about it | `AshStrangler.Obligations` |
  | *how* PostgreSQL carries each write | `AshStrangler.Mechanism` |
  | what is *emitted* | `AshStrangler.Sql.View`, `.Triggers`, `.ReverseView`, `.Notify` |
  | how any of it becomes SQL | `AshStrangler.Sql.Printer`, and nothing else |
  | which columns feed which attribute | `AshStrangler.Lineage` |

  The compatibility DDL is emitted by `mix ash_strangler.gen.migration` rather
  than by `mix ash.codegen`, and it has to be: see
  `AshStrangler.Verifiers.VerifyNotMigrated` for why there is no configuration in
  which `custom_statements` works for a view-backed resource.

  ## The legacy relation is a resource too

  `source` takes a **twin** module — the legacy relation declared as a private,
  read-only, `migrate? false` Ash resource, generated by
  `mix ash_strangler.gen.twin`. That is what makes `expr(first_name)` resolve to a
  typed column, and it is what collapsed four DSL constructs (`cast:`, `index`,
  `join`/`on:`, and the diagram's column-guessing regex) into things Ash already
  has. See `AshStrangler.Twin`.

  ## Diagrams

  When the optional `:ash_diagram` dependency is present this extension also
  implements `AshDiagram.Data.Extension`, so a strangled resource carries its
  legacy source into any entity-relationship diagram drawn of the application —
  including the ones `mix ash.generate_resource_diagrams` and `Clarity` produce,
  neither of which knows this package exists.

  That is the point of the hook: the legacy table is part of the data model for
  as long as the migration runs, and a diagram that omits it is describing a
  system that does not exist yet. For the mapping itself, drawn column by
  column, see `AshStrangler.Diagram.Mapping`.
  """

  use Spark.Dsl.Extension,
    sections: AshStrangler.Dsl.sections(),
    transformers: [
      AshStrangler.Transformers.MarkKeyGenerated
    ],
    verifiers: [
      # Order matters. `VerifyTwin` runs first because every verifier after it
      # builds lenses, and a lens over a stale twin fails in a place that names
      # neither the column nor the fix.
      AshStrangler.Verifiers.VerifyTwin,
      AshStrangler.Verifiers.VerifyCompleteMapping,
      AshStrangler.Verifiers.VerifyNotMigrated,
      AshStrangler.Verifiers.VerifyNotRedundant,
      AshStrangler.Verifiers.VerifyTimestampZones,
      AshStrangler.Verifiers.VerifyDerivedWritability,
      AshStrangler.Verifiers.VerifyJoinedWritesRefused,
      AshStrangler.Verifiers.VerifyObligations,
      AshStrangler.Verifiers.VerifyNoUpserts,
      AshStrangler.Verifiers.VerifyReverseMappable,
      AshStrangler.Verifiers.VerifyIdentitiesBacked,
      AshStrangler.Verifiers.VerifyPhaseTransition
    ]

  # Only when `:ash_diagram` is there to define the behaviour. Declaring it
  # unconditionally would make the extension -- which every strangled resource
  # depends on -- fail to compile without an optional dependency.
  if Code.ensure_loaded?(AshDiagram.Data.Extension) do
    @behaviour AshDiagram.Data.Extension

    alias AshDiagram.EntityRelationship.Attribute
    alias AshDiagram.EntityRelationship.Entity
    alias AshDiagram.EntityRelationship.Relationship

    @doc false
    @impl AshDiagram.Data.Extension
    def supports?(AshDiagram.Data.EntityRelationship), do: true
    def supports?(_creator), do: false

    @doc false
    @impl AshDiagram.Data.Extension
    def extend_diagram(AshDiagram.Data.EntityRelationship, diagram) do
      # `extend_diagram/2` is handed the diagram and nothing else, so the
      # resources are recovered from the entities already in it. That is not a
      # workaround -- it is what keeps the hook honest, because it can only
      # annotate resources the diagram actually drew.
      strangled = diagram.entries |> Enum.flat_map(&strangled_entity/1) |> Enum.uniq()

      %{diagram | entries: diagram.entries ++ legacy_entries(strangled)}
    end

    def extend_diagram(_creator, diagram), do: diagram

    defp strangled_entity(%Entity{id: id}) do
      module = id |> IO.iodata_to_binary() |> resolve()

      if module, do: [{id, module}], else: []
    end

    defp strangled_entity(_entry), do: []

    defp resolve(id) do
      module = Module.concat([id])

      if Code.ensure_loaded?(module) and
           function_exported?(module, :spark_dsl_config, 0) and
           AshStrangler.Info.strangled?(module),
         do: module
    rescue
      ArgumentError -> nil
    end

    defp legacy_entries(strangled) do
      entities =
        strangled
        |> Enum.group_by(fn {_id, module} -> AshStrangler.Info.relation(module) end)
        |> Enum.map(fn {relation, members} -> legacy_entity(relation, members) end)

      relationships =
        Enum.map(strangled, fn {id, module} ->
          %Relationship{
            left: {AshStrangler.Info.relation(module), :exactly_one},
            right: {IO.iodata_to_binary(id), :zero_or_more},
            identifying?: false,
            label: "strangler"
          }
        end)

      entities ++ relationships
    end

    defp legacy_entity(relation, members) do
      attributes =
        members
        |> Enum.flat_map(fn {_id, module} -> legacy_columns(module) end)
        |> Enum.uniq()
        |> Enum.sort()
        |> Enum.map(&%Attribute{type: "column", name: &1})

      %Entity{id: relation, label: relation, attributes: attributes}
    end

    # Only the columns the mapping actually names -- but that set is now a FACT
    # rather than a guess, and this is where the difference used to be dangerous.
    #
    # In 0.1 this called `Diagram.Sql.columns/2`, a regex over the `from:` string
    # that returned `:unresolved` when it found nothing. The mapping diagram
    # degraded visibly on that, drawing a rhombus saying so. Here it degraded to
    # `[]`, silently, so a column the regex could not parse simply vanished from
    # every entity-relationship diagram the application draws -- including the ones
    # `mix ash.generate_resource_diagrams` and Clarity produce.
    #
    # `AshStrangler.Lens`'s `sources` are the references the expression was built
    # from, so there is no failure mode left to degrade.
    defp legacy_columns(module) do
      twin = AshStrangler.Info.twin(module)

      module
      |> AshStrangler.Lens.for_resource()
      |> Enum.flat_map(& &1.sources)
      |> Enum.map(fn {path, attribute} -> column_label(twin, path, attribute) end)
      |> Enum.uniq()
    end

    # A reference through a relationship keeps its path, because that is how the
    # diagram knows the column belongs to a different table.
    defp column_label(twin, [], attribute) do
      AshStrangler.Twin.column!(twin, attribute)
    rescue
      _ -> to_string(attribute)
    end

    defp column_label(_twin, path, attribute) do
      Enum.map_join(path ++ [attribute], ".", &to_string/1)
    end
  end
end
