# SPDX-FileCopyrightText: 2026 Luke Galea
#
# SPDX-License-Identifier: MIT

defmodule AshStrangler.Twin do
  @moduledoc """
  The legacy relation, declared as an ordinary Ash resource.

  A *twin* is a private, read-only, `migrate? false` `AshPostgres` resource over
  a table this application does not own and never will. It is generated by
  `mix ash_strangler.gen.twin`, which introspects the live database — so the
  legacy schema is **read**, not retyped.

      defmodule MyApp.Legacy.Accounts do
        use Ash.Resource,
          domain: MyApp.Legacy,
          data_layer: AshPostgres.DataLayer,
          extensions: [AshStrangler.Twin]

        postgres do
          table "accounts"
          schema "legacy"
          repo MyApp.Repo
          migrate? false
        end

        attributes do
          attribute :id, :integer, primary_key?: true
          attribute :email, :string
          attribute :first_name, :string
        end

        identities do
          identity :index_accounts_on_email, [:email]
        end
      end

  ## What the twin buys, and why nothing else does

  `expr(first_name)` has to mean something. Without a resource behind it,
  `first_name` is a bare atom: `AshSql` refuses to render it and
  `Ash.Filter.hydrate_refs/2` has nothing to look it up on. Declaring the legacy
  columns *inline* inside the `strangler` block would satisfy the printer, but it
  would restate the legacy schema by hand — which is the defect the whole
  redesign is about. So the twin is a real resource, and four DSL constructs
  collapse into things Ash already has:

  | Deleted | Replaced by |
  |---|---|
  | `cast: :citext` | the twin attribute's type against the target attribute's type |
  | `index "…", unique: true, columns: [...]` | an `identity` on the twin, checked against `pg_index` by `mix ash_strangler.check` |
  | `join "legacy.addresses", as: "addr", on: "addr.account_id = accounts.id"` | a relationship on the twin; the mapping reads `expr(address.city)` |
  | `AshStrangler.Diagram.Sql`'s regex and its `known_columns:` escape hatch | typed attributes, so lineage is a fact |

  ## The twin is a snapshot, and snapshots go stale

  It is generated by introspection, so a column the legacy application's next
  migration adds is invisible until the twin is regenerated. That is a real cost
  and the honest mitigation is a check rather than a promise:
  `mix ash_strangler.check` diffs every twin against `information_schema` and
  reports the difference. Run it in CI, or the typed layer inherits exactly the
  staleness problem it was built to remove.

  ## Joins are always `LEFT`, and that is now structural rather than a default

  The old DSL let a join declare `type: :inner` and argued at length that `:left`
  had to be the default, because an `INNER JOIN` *removes rows* — a legacy row
  with no match disappears from the view, so the new application sees fewer
  records than the old one and nothing reports it. Deriving the join from a
  relationship removes the option entirely: a relationship describes which rows
  *relate*, not which rows *survive*. An author who genuinely wants to drop
  unmatched rows writes a `filter` on the read action, where it is visible as a
  filter.
  """

  use Spark.Dsl.Extension

  @doc """
  True when `module` is usable as a twin: a compiled `AshPostgres` resource with a
  table.

  Deliberately not "has the `AshStrangler.Twin` extension". The extension is
  documentation and a marker; a hand-written `AshPostgres` resource over a legacy
  table works identically, and refusing it would be gatekeeping with no
  mechanism behind it.
  """
  @spec twin?(term()) :: boolean()
  def twin?(module) when is_atom(module) do
    Code.ensure_loaded?(module) and
      function_exported?(module, :spark_dsl_config, 0) and
      Ash.Resource.Info.resource?(module) and
      not is_nil(AshPostgres.DataLayer.Info.table(module))
  end

  def twin?(_other), do: false

  @doc """
  The twin's relation, schema-qualified: `"legacy.users"`.

  Unqualified when the twin declares no schema, which relies on `search_path`
  exactly as much as a `postgres do table "users" end` with no schema already
  does.
  """
  @spec relation(Ash.Resource.t()) :: String.t()
  def relation(twin) do
    table = table!(twin)

    case AshPostgres.DataLayer.Info.schema(twin) do
      nil -> table
      schema -> "#{schema}.#{table}"
    end
  end

  @doc "The twin's bare table name, which is also the default alias for it."
  @spec table!(Ash.Resource.t()) :: String.t()
  def table!(twin) do
    AshPostgres.DataLayer.Info.table(twin) ||
      raise ArgumentError,
            "#{inspect(twin)} is used as a strangler `source` but has no `postgres do table \"...\" end`"
  end

  @doc """
  The real column name behind an attribute.

  Ash's `source:` option is the mapping from attribute name to column name, so a
  twin whose generator found a column Elixir would not want as an atom — `"Type"`,
  `"order"` — carries it there and this reads it.
  """
  @spec column!(Ash.Resource.t(), atom()) :: String.t()
  def column!(twin, attribute) do
    case Ash.Resource.Info.attribute(twin, attribute) do
      nil ->
        raise ArgumentError, unknown_attribute_message(twin, attribute)

      %{source: source} when not is_nil(source) ->
        to_string(source)

      %{name: name} ->
        to_string(name)
    end
  end

  @doc "The Ash type of a twin attribute, for deriving casts and checking type agreement."
  @spec type!(Ash.Resource.t(), atom()) :: Ash.Type.t()
  def type!(twin, attribute) do
    case Ash.Resource.Info.attribute(twin, attribute) do
      nil -> raise ArgumentError, unknown_attribute_message(twin, attribute)
      %{type: type} -> type
    end
  end

  @doc "Every attribute name the twin declares."
  @spec columns(Ash.Resource.t()) :: [atom()]
  def columns(twin), do: twin |> Ash.Resource.Info.attributes() |> Enum.map(& &1.name)

  @doc """
  The sets of columns the twin declares unique, as `MapSet`s of column-name
  strings.

  This is what `AshStrangler.Verifiers.VerifyIdentitiesBacked` compares an Ash
  identity against, and what `mix ash_strangler.check` compares `pg_index`
  against.
  """
  @spec unique_column_sets(Ash.Resource.t()) :: MapSet.t(MapSet.t(String.t()))
  def unique_column_sets(twin) do
    identities = Ash.Resource.Info.identities(twin)
    primary_key = Ash.Resource.Info.primary_key(twin)

    sets =
      for identity <- identities,
          into: MapSet.new(),
          do: MapSet.new(identity.keys, &column!(twin, &1))

    if primary_key == [] do
      sets
    else
      MapSet.put(sets, MapSet.new(primary_key, &column!(twin, &1)))
    end
  end

  @doc """
  Resolves a relationship path into the joins needed to reach it.

  Returns `{:ok, [join]}` where each join is
  `%{relation:, alias:, on:, relationship:}` in the order they must appear in the
  `FROM` clause, or `{:error, message}` when a step of the path is not a
  relationship on the twin.

  Only `belongs_to` and `has_one` are resolvable. A `has_many` or `many_to_many`
  would multiply rows — one legacy account with three addresses becoming three
  view rows, and therefore three `Customer` records where the old application had
  one. That is the fan-out failure the tool exists to refuse, so it is refused
  here by name rather than measured later.
  """
  @spec joins_for(Ash.Resource.t(), [atom()]) ::
          {:ok,
           [%{relation: String.t(), alias: String.t(), on: String.t(), relationship: term()}]}
          | {:error, String.t()}
  def joins_for(twin, path) do
    path
    |> Enum.reduce_while({:ok, {twin, table!(twin), []}}, fn step, {:ok, {current, alias, acc}} ->
      case Ash.Resource.Info.relationship(current, step) do
        nil ->
          {:halt,
           {:error,
            "#{inspect(current)} has no relationship #{inspect(step)}. " <>
              "A mapping that reads `expr(#{Enum.join(path, ".")})` needs one, and it must be a " <>
              "`belongs_to` or `has_one`."}}

        %{cardinality: :many} = relationship ->
          {:halt,
           {:error,
            "relationship #{inspect(step)} on #{inspect(current)} is a #{relationship.type}, which " <>
              "returns many rows. Joining it would multiply view rows — one legacy row becoming " <>
              "three — so the new application would report more records than the old one. Read it " <>
              "through its own resource instead."}}

        relationship ->
          destination = relationship.destination
          step_alias = to_string(step)

          join = %{
            relation: relation(destination),
            alias: step_alias,
            on:
              "#{step_alias}.#{column!(destination, relationship.destination_attribute)} = " <>
                "#{alias}.#{column!(current, relationship.source_attribute)}",
            relationship: relationship
          }

          {:cont, {:ok, {destination, step_alias, acc ++ [join]}}}
      end
    end)
    |> case do
      {:ok, {_resource, _alias, joins}} -> {:ok, joins}
      {:error, message} -> {:error, message}
    end
  end

  @doc """
  The resource a relationship path lands on, for resolving the attribute at the
  end of it.
  """
  @spec resource_at(Ash.Resource.t(), [atom()]) :: {:ok, Ash.Resource.t()} | {:error, String.t()}
  def resource_at(twin, []), do: {:ok, twin}

  def resource_at(twin, [step | rest]) do
    case Ash.Resource.Info.relationship(twin, step) do
      nil -> {:error, "#{inspect(twin)} has no relationship #{inspect(step)}"}
      relationship -> resource_at(relationship.destination, rest)
    end
  end

  defp unknown_attribute_message(twin, attribute) do
    known = twin |> columns() |> Enum.sort() |> Enum.map_join(", ", &inspect/1)

    """
    #{inspect(twin)} has no attribute #{inspect(attribute)}.

    It declares: #{known}

    If the legacy table really has that column, the twin is stale — regenerate it:

        mix ash_strangler.gen.twin #{inspect(twin)}
    """
  end
end
